---
sidebar: sidebar 
permalink: Management.Applications.application_entitlement_workflow.html 
summary: 在 VDS 中为最终用户部署应用程序的分步指南 
keywords:  
---
= 应用程序授权
:allow-uri-read: 




== 概述

VDS 内置了强大的应用程序自动化和授权功能。通过此功能，用户可以在连接到同一会话主机时访问不同的应用程序。这是通过一些自定义 GPO 隐藏快捷方式以及自动化有选择地在用户桌面上放置快捷方式来实现的。


NOTE: 此工作流仅适用于适用场景 RDS 部署。有关 AVD 应用程序授权文档，请参见 link:Management.Applications.AVD_application_entitlement_workflow.html["适用于 AVD 的应用程序授权工作流"]

可以直接将应用程序分配给用户，也可以通过 VDS 中管理的安全组分配应用程序。

.总体而言，应用程序配置过程遵循以下步骤。
. 将应用程序添加到应用程序目录
. 将应用程序添加到工作空间
. 在所有会话主机上安装应用程序
. 选择快捷方式路径
. 将应用程序分配给用户和 / 或组



NOTE: 步骤 3 和 4 可以通过脚本化事件完全自动化，如下图所示

.视频演练
video::19NpO8v15BE[youtube]


== 将应用程序添加到应用程序目录

VDS 应用程序授权从应用程序目录开始，此列表列出了可部署到最终用户环境的所有应用程序。

.要将应用程序添加到目录中，请按照以下步骤进行操作
. 登录到 VDS https://manage.cloudworkspace.com[] 使用主管理员凭据。
. 在右上角，单击用户名旁边的箭头图标，然后选择设置。
. 单击应用程序目录选项卡。
. 单击应用程序目录标题栏中的添加应用程序选项。
. 要添加一组应用程序，请选择导入应用程序选项。
+
.. 此时将显示一个对话框，其中提供了一个要下载的 Excel 模板，用于为应用程序列表创建正确的格式。
.. 对于此评估， NetApp VDS 已创建了一个用于导入的应用程序列表示例，可在此处找到。
.. 单击上传区域并选择应用程序模板文件，然后单击导入按钮。


. 要添加单个应用程序，请选择添加应用程序按钮，此时将显示一个对话框。
+
.. 输入应用程序的名称。
.. 外部 ID 可用于输入内部跟踪标识符，例如产品 SKU 或计费跟踪代码（可选）。
.. 如果要以订阅产品的形式报告应用程序，请选中订阅框（可选）。
.. 如果产品未按版本（例如 Chrome ）安装，请选中不需要版本复选框。这样可以在安装 " 持续更新 " 产品时不跟踪其版本。
.. 相反，如果某个产品支持多个命名版本（例如： QuickBooks ），则需要选中此框，以便可以安装多个版本，并在可授权给和最终用户的应用程序列表中为每个可用版本设置 VDS 专用版本。
.. 如果不希望 VDS 为此产品配置桌面图标，请选中 " 无用户桌面图标 " 。这用于 SQL Server 等 " 后端 " 产品，因为最终用户没有可访问的应用程序。
.. " 应用程序必须关联 " 强制要求安装关联的应用程序。例如，客户端服务器应用程序可能还需要安装 SQL Server 或 MySQL 。
.. 选中需要许可证复选框表示 VDS 应先请求为该应用程序的安装上传许可证文件，然后再将该应用程序状态设置为活动状态。此步骤在 VDS 的 " 应用程序 " 详细信息页面上执行。
.. 对所有人可见—应用程序授权可以限制为多通道层次结构中的特定子合作伙伴。出于评估目的，请单击复选框，以便所有用户都可以在其可用应用程序列表中看到它。






== 将应用程序添加到工作空间

要开始部署过程，您需要将此应用程序添加到工作空间中。

.要执行此操作，请执行以下步骤：
. 单击 Workspaces
. 向下滚动到应用程序
. 单击添加。
. 选中应用程序复选框，输入所需信息，单击添加应用程序，然后单击添加应用程序。




== 手动安装应用程序

将应用程序添加到工作空间后，您需要在所有会话主机上安装该应用程序。这可以手动完成，也可以自动完成。

.要在会话主机上手动安装应用程序，请执行以下步骤
. 导航到服务板。
. 单击服务板任务。
. 单击服务器名称以作为本地管理员进行连接。
. 安装应用程序，确认此应用程序的快捷方式位于 " 开始 " 菜单路径中。
+
.. 对于 Server 2016 和 Windows 10 ： C ： \ProgramData\Microsoft\Windows\Start Menu" \Programs.


. 返回到服务板任务，单击浏览，然后选择快捷方式或包含快捷方式的文件夹。
. 无论您选择哪个选项，分配应用程序时最终用户桌面上都会显示的内容。
. 当一个应用程序实际上是多个应用程序时，文件夹非常好。例如，可以更轻松地将 Microsoft Office 部署为文件夹，并将每个应用程序作为文件夹中的快捷方式。
. 单击 Complete Installation 。
. 如果需要，打开已创建图标添加服务板任务并确认已添加此图标。




== 将应用程序分配给用户

应用程序授权由 VDS 处理，应用程序可通过三种方式分配给用户

.将应用程序分配给用户
. 导航到用户详细信息页面。
. 导航到应用程序部分。
. 选中此用户所需的所有应用程序旁边的框。


.将用户分配给应用程序
. 导航到 " 工作空间详细信息 " 页面上的 " 应用程序 " 部分。
. 单击应用程序的名称。
. 选中应用程序用户旁边的框。


.将应用程序和用户分配给用户组
. 导航到用户和组详细信息。
. 添加新组或编辑现有组。
. 将用户和应用程序分配给组。

