---
sidebar: sidebar 
permalink: Reference.Release_Notes.cwms_v5.2_release_notes.html 
summary: NetApp VDS 发行说明 v5.2 
keywords:  
---
= Cloud Workspace Management Suite —版本 5.2
:allow-uri-read: 



NOTE: 对于 WCMS 5.2 版，不再重复发布任何版本—所有版本都将视为修补程序。



== WCMS 5.2 版本： 2019 年 12 月 2 日，星期一

组件： 5.2 Cloud Workspace Management Suite 时间： 2019 年 12 月 2 日星期一晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。

此版本周期无更新。



== WCMS 5.2 版本： 2019 年 11 月 14 日，星期四

组件： 5.2 Cloud Workspace Management Suite 时间： 2019 年 11 月 14 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。

此版本周期无更新。



== WCMS 5.2 版本： 2019 年 10 月 31 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 10 月 31 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。

此版本周期无更新。



== WCMS 5.2 版本： 2019 年 10 月 17 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 10 月 17 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。

此版本周期无更新。



== WCMS 5.2 版本： 2019 年 10 月 3 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 10 月 3 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。

此版本周期无更新。



== WCMS 5.2 版本： 2019 年 9 月 19 日，星期四

组件： 5.2 Cloud Workspace Management Suite 时间： 2019 年 9 月 19 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 云工作空间管理套件

默认情况下， Azure 部署的资源分配类型为 " 已修复 " ； 如果选择的 VM 系列 / 大小是由管理员在 WCMS 中定义的 VM ，则添加用户活动的搜索功能审核功能错误修复 5 分钟后错误显示会话非活动超时警告的错误修复，而不是 55 分钟用户支持角色修复—这是具有此角色的一部分管理员 无法查看其组织的用户列表用户排序修复程序—按用户名排序可以正常运行，而不是按状态排序确保主客户端报告存在；为非主软件合作伙伴隐藏不适用的 SPLA 报告



=== 云工作空间工具和服务

增强了后台密码加密如果管理员在 CMGR1 中将密码到期日期设置为空，则密码强制实施通知（ Pen ）的错误修复功能无法按预期使用 " 下次登录时更改密码 " 功能



=== 适用于 Azure 的 Cloud Workspace 设置应用

适用于国际管理员的修复方法—如果国家或地区不是美国，则此方法需要使用州。通过合作伙伴管理链接（ PAL ）应用 Cloud跨 接以在订阅级别呈现和未来的 Azure 部署



== WCMS 5.2 版本： 2019 年 9 月 5 日，星期四

组件： 5.2 Cloud Workspace Management Suite 时间： 2019 年 9 月 5 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 云工作空间管理套件

仅用户支持角色的更新： * 添加搜索 / 筛选用户功能 * 包括用户及其连接的连接状态列 * 提供对 " 下次登录时强制更改密码 " 功能的访问权限 * 删除删除客户端功能的可见性在一小时不活动后强制注销 CWMS 对于显示的问题描述进行修复 对于工作负载计划设置为始终关闭的环境显示的显示问题描述，如果查看资源分配类型设置为 " 固定修复 " 的 VM 角色时 VM 系列 / 大小显示不正确， 尽管在后台权限更新后已正确设置为始终关闭，但如果 CMS 管理员无法访问 CEMS 中的资源功能，请删除资源计划选项卡



=== 云资源应用程序

更新了功能—支持使用命令行



=== 云工作空间工具和服务

支持 vCloud REST 接口



== WCMS 5.2 版本： 2019 年 8 月 22 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 8 月 22 日星期四晚上 10 点至晚上 11 点东部影响：最终用户对 Cloud Workspace 桌面和应用程序服务的访问将保持不间断。您仍可访问 Cloud Workspace Management Suite 。



=== 云工作空间管理套件

修复某些监控器大小在用户配置文件中显示的问题描述为非动态应用程序服务添加澄清消息，通知管理员更改可能需要几分钟才能生效为非动态应用程序服务添加重新刷新按钮，以便更容易判断是否有新的客户端 / 用户 已添加



=== 适用于 Azure 的 Cloud Workspace 设置

在链接到现有的 CWMS 帐户改进后，添加对 MFA 注册流程的支持—链接到新的和改进的公有 KB 改进后的配置说明—链接将在新选项卡中打开



=== 云工作空间工具和服务

修复旧版（ 2008 R2 ）环境中 SSL 证书管理的错误为证书强制实施和生命周期管理提供了额外的运行状况检查



== WCMS 5.2 版本： 2019 年 8 月 8 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 8 月 8 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。

此版本无更新。



== WCMS 5.2 版本： 2019 年 7 月 25 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 7 月 25 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 CWA" 设置 "

显示一条消息 " 配置后 " ，指示 CWA" 设置用户访问 Cloud跳 线公有知识库，他们可以在该知识库中查看后续步骤以及如何优化部署改进了在注册过程中对美国以外国家 / 地区的处理方式。添加了一个字段来确认新创建的 的密码 在 CWA 设置过程中登录在不需要 RDS 许可证的情况下删除 SPLA 许可部分



=== 5.2 云工作空间管理套件

改进了在单个服务器部署中对 CCMS 管理员的 HTML5 连接处理错误修复了重新启动用户处理（以前失败时）的情形 导致出现 "Internal Server Error" 消息 Remove SPLA licensing section under circumstances where RDS licenses will not be required include Automatic SSL certificate handling and Automatic SMTP to the Provising Wizard in CWMS



=== 5.2 Cloud Workspace 工具和服务

当 VDI 用户在将其虚拟机设置为关闭时注销虚拟机时，请关闭此 VM Azure Backup 增强功能—将 TSD1 服务器还原为虚拟机时， 还原为 TS VM ，而不是另一个 TSD VM 以 Steam内联 方式准备 Azure VM for Azure Backup ，以提高后端处理速度和安全性



=== 5.2 REST API

改进了服务器信息的处理方式，从而加快了按需唤醒服务器的加载速度



== WCMS 5.2 版本： 2019 年 7 月 11 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 7 月 11 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 Cloud Workspace 工具和服务

持续后台安全增强持续增强自动生成证书的稳定性增强最低特权方法改进—调整使用权限较少 / 受通用锁定影响较小的帐户以执行夜间重新启动 Azure 部署的集成备份改进 GCP 部署的集成备份改进错误修复 如果服务器已经进行了正确的过程增强，可以根据需要手动管理证书，则不再需要重新启动服务器以应用资源调整



== WCMS 5.2 版本： 2019 年 6 月 20 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 6 月 20 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

改进了通过 CRA 流程导入到 CEMS 中的用户的处理方式在工作空间模块的服务器部分中正确显示存储，以显示一组在 WCMS Web 界面底部进行了年度更新的场景



=== 5.2 Cloud Workspace 工具和服务

增强的自动化证书自动化功能



=== 5.2 REST API

显示更正—再次打开实时扩展功能允许为高级用户角色（ VDI 用户）创建默认备份计划时，显示先前在实时扩展功能中输入的正确值。



== WCMS 5.2 版本： 2019 年 6 月 6 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 6 月 6 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 Cloud Workspace 工具和服务

改进了对平台通知的多封电子邮件的处理错误修复了工作负载计划未正确关闭服务器的部分情形错误修复了从 Azure Backup 还原服务器未还原正确存储类型与的部分情形默认存储类型



=== 5.2 CWA" 设置 "

在 CWA 设置过程中持续增强的安全性改进了子网和网关设置的自动处理改进了注册过程中在后台处理用户帐户的过程，其中包括在用户在 CWA 设置过程中保留超过 1 小时时刷新令牌的过程



== WCMS 5.2 版本： 2019 年 5 月 23 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 5 月 23 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

改进了 " 工作空间 " 模块中 AVD 选项卡中的链接错误修复，适用于以下情形：单击数据中心模块中指向工作空间的链接不会将您转至该工作空间错误修复：更新主管理员的联系信息将删除其 指定为主管理员



== WCMS 5.2 版本： 2019 年 5 月 9 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 5 月 9 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 Cloud Workspace 工具和服务

改进了包含数百到数千个 VM 的部署的可扩展性



== WCMS 5.2 版本： 2019 年 4 月 25 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 4 月 25 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

接口改进—如果 Azure 或 GCP 中的服务器未启用备份，请从服务器的备份部分中删除大小列



=== 5.2 Cloud Workspace 工具和服务

错误修复：资源更改完成后，更改 RDP 和 / 或 HTML5 网关服务器的资源无法使其恢复联机的情形



=== 5.2 REST API

改进了初始 MFA 配置的处理方式，无论何种情形



=== 5.2 CWA" 设置 "

支持现有的 WCMs 帐户，支持间接 CSP 正确配置并简化现有合作伙伴的流程 Azure Active Directory 域服务的额外验证—如果选择了 Azure Active Directory 域服务，但该服务已到位，则会显示错误



== WCMS 5.2 版本： 2019 年 4 月 11 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 4 月 11 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

配置收集的错误修复—使用未显示桌面图标的应用程序保存配置收集将不再显示错误，错误修复—解决从问题描述启动已停止的平台服务器时由于没有合作伙伴而显示错误的问题 已附加代码



=== 5.2 Cloud Workspace 工具和服务

在 vCloud 部署中删除服务器的稳定性增强—如果在一个 vApp 中发现多个 FMS ， 仅删除虚拟机而不是删除 vApp 添加不在基础架构服务器上安装通配符证书的选项 AzureAD 中克隆 TSD 服务器的改进服务器资源报告—处理具有多个 IP 地址的服务器如果列出，则对部分情形进行错误修复 在 Azure Classic 中尝试使用前缀克隆 VM 时，服务器备份不会加载以供审核错误修复（所有新部署和最新部署均使用 AzureRM ） Server 2008 R2 服务器资源报告中未正确报告 DNS 错误的错误修复错误修复在虚拟机管理程序（而不是 AD ）中删除虚拟机时未发送公司资源报告的错误修复 并且，在虚拟机管理程序本身中找不到 Azure 备份（仅在 AzureRM 部署中）



=== 5.2 CWA" 设置 "

添加一种方法以验证所选配置到的区域是否可用 Azure Active Directory 域服务添加其他检查以解决部分场景中的 DNS 超时问题删除 B2S 作为 CMGR1 部署的目标，因为它会减慢部署过程的速度



== WCMS 5.2 版本： 2019 年 3 月 28 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 3 月 28 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

将 Azure Virtual Desktop 部分添加到 CWMS 界面允许 CEMS 管理员在 " 设置 "->" 标识 " 下设置公司标识更新自定义应用程序目录中的应用程序时添加外部 ID 要求



=== 5.2 Cloud Workspace 工具和服务

进一步简化和改进适用于 Azure 的云工作空间（ CWA） 部署流程不再需要高级存储帐户在 Azure RM 部署中创建具有高级存储的 VM 解决了应用程序使用情况跟踪报告未捕获使用情况数据的部分情形下的问题描述解决方案 更新 HTML5 门户服务器上的证书可能会导致错误的问题描述，因为 HTML5 门户服务器许可已更新密码到期通知的错误修复使用 Azure Active Directory 域服务时不更新密码调整了密码到期通知写入日志文件的位置



=== 5.2 REST API

在数据中心模块中启动 / 停止平台服务器（非客户服务器）的错误修复



=== 5.2 CWA" 设置 "

改进了部署期间的 FTP 角色设置改进了确保管理员每次访问 CWA 设置过程时都能看到最新版本的机制改进了对部署期间超时元素的处理在部署中错误标记为使用 Azure AD 的情况下修复了错误



== WCMS 5.2 次要版本： 2019 年 3 月 14 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 3 月 14 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

将 " 应用程序监控 " 功能的名称更改为 " 应用程序使用情况跟踪 " 应用修复程序，修复程序刷新对脚本化事件的搜索不会重新使用选定的开始 / 结束日期默认文件审核以日期筛选器设置为当前日期前一天开始， 简化返回的数据量 Azure 集成备份的错误修复在部分情形下，将备份还原到服务器的功能无法按预期运行解决了更新属于应用程序服务的客户端时出现的应用程序错误提示



=== 5.2 REST API

Azure 安全保护—添加 Azure AD 用户时，请确保其电子邮件地址尚未添加到帐户中。错误修复—为客户端添加应用程序并同时创建组时， 按预期将用户添加到组在禁用对 RDSH 服务器的访问时添加验证步骤，以确保在服务器重新启动后仍可应用此步骤在将应用程序添加到受影响的组时， CWA" 工作流自动化的常规改进 " 错误修复部分情形 该组的其他用户



=== 5.2 CWA" 设置 "

在部署过程中为订阅列表添加一个刷新选项将旧版已降级的 MobileDrive 服务的部署标志自动设置为 False Azure 中的其他自动化保护和检查



== WCMS 5.2 次要版本： 2019 年 2 月 28 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 2 月 28 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

提高了对在 CEMS 界面中取消为用户选择 "VDI User" 复选框时会发生什么情况（删除 VDI 用户的服务器）以及在不希望删除服务器后端对时间戳处理的改进时如何继续显示的清晰性和确认消息



=== 5.2 Cloud Workspace 工具和服务

更新了 Azure 域服务中许可证服务器名称的设置后台改进了用户在登录到云工作空间后可以更改自己密码的过程更新了原生 2FA 以反映启用了罕见设置时为 2FA 修复的 Cloud跨 接图像错误



=== 5.2 CWA" 设置 "

CWA" 设置向导中的其他帮助 / 支持内容向 CWA" 设置向导添加协议条款和定价改进了检测订阅配额和权限的机制简化了基于 Azure Active Directory 域服务的部署在后台改进了存储帐户名称格式 FTP 服务器的错误修复 设置



== WCMS 5.2 次要版本： 2019 年 2 月 14 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 2 月 14 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

提高用户管理操作的性能启用了其他日志记录以显示谁请求在数据中心任务历史记录中更改组。解决标准应用程序目录中应用程序未显示在部分情形中的问题描述使用动态解决应用程序服务中的问题描述 配置如果两个同名应用程序从 CWMS 5.1 界面删除 SDDC 创建向导 * 如果您运行的是 5.1 上的 SDDC ，并且您希望配置新的 SDDC ， 请联系 support@cloudjumper.com 以计划升级到 CWMS 5.2 ，更正在 CWMS 的 API 用户创建屏幕中出现的拼写错误



=== 5.2 Cloud Workspace 工具和服务

在基于 vCloud 的 SDDC 中，如果基于 vCloud 的 SDDC 中的连接到期，请重新登录到虚拟机管理程序，并增加等待服务器启动时的默认超时值。改进了 Cloud跳 线管理访问的限制



=== 5.2 REST API

在通过 CEMS 5.1 界面配置新 SDDC 时，显示的消息将为 " 只有在使用 WCMS 5.2 版时才支持创建新数据中心 " 。



=== 5.2 CWA" 设置 "

改进了自动错误处理功能



== WCMS 5.2 次要版本： 2019 年 1 月 31 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 1 月 31 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

将 Cloud Workspace 客户端服务器的连接信息添加到 Cloud Workspace 客户端的概述部分在 CCMS 帐户设置中添加一个可编辑字段，用于输入 Azure AD 租户 ID 在新 Azure 部署中使用最新版本的 Microsoft 标准存储改进了 Azure 集成， 要求 Azure 部署中的集成备份至少保留 1 天改进应用程序服务部署动态配置中的处理方式将服务器存储资源的清点日期添加到 " 服务器 " 模块的该部分显示应用程序是在配置时配置给用户的 用户的状态仍为待定云工作空间如果用户是 VDI 用户，则在用户页面上显示 VDI 服务器如果服务器是为 VDI 用户提供的， 在 " 服务器 " 页面上显示用户解决问题描述在某些情况下，如果用户的用户名具有打开的服务板任务，则从 远程访问虚拟机失败



=== 5.2 Cloud Workspace 工具和服务

改进了用户全天登录时实时扩展的处理方式添加了未来按需唤醒的自动化前提条件改进添加了未来工作负载计划的自动化前提条件改进解决了使用适用于 VDI 服务器的 Windows 10 无法在 Azure Active 中正确启用远程注册表服务的问题描述问题 目录域服务部署解决了在 Azure Active Directory 域服务部署中使用适用于 VDI 服务器的 Windows 10 未正确为本地远程桌面用户组设置安全组的问题描述修改 PCI 合规性设置功能，使其在未启用时不执行任何操作，而不是强制执行 默认配置设置可在工作负载计划中解决问题描述，以便在计划关闭服务器时注销并启用了按需唤醒的用户可以关闭服务器。修复在 ProfitBricks 公有云中克隆服务器时的错误修复克隆服务器检查的错误 在 VDI 用户方案中，服务器名称的服务器前缀不会重复添加在每晚报告中检查是否存在未使用有效配置收集的缓存客户代码改进了在虚拟机管理程序中不存在虚拟机管理程序且 CWAgent 需要更新时处理异常的方式解决问题描述 通过密码到期通知重置密码以正确强制实施密码历史记录



=== CWA" 设置 "

实施选项以自动配置 SMTP 设置为位置列表添加验证选项以检查订阅是否具有足够的配额和权限以在选定 Azure 区域中创建 VM 添加了功能，可在结束时删除不需要的 CloudWorkspace 和其他具有管理权限的服务帐户 Azure 中的配置过程通知手动上传 DNS 证书的用户已通过验证解决了在某些情况下 ThinPrint 安装不按预期安装的问题描述问题



== WCMS 5.2 次要版本： 2019 年 1 月 17 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2019 年 1 月 17 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

现在，工作负载计划界面会将问题描述显示为第一列，并将计划名称更改为自定义计划错误修复用于在 Azure 部署中显示平台服务器备份的错误修复适用于最终用户自行管理应用程序服务的使用情形组织不会使用的情形 已设置任何 Cloud Workspace 服务



=== 5.2 Cloud Workspace 工具和服务

添加了对 PCI v3 合规性安全性增强功能的支持：新的 CWMS 部署将使用本地管理员而不是用于运行 CWAgent 进程的域管理员。支持 AzureRM 部署中的 Windows Server 2019 * 注意： Microsoft 在此版本中不支持 Microsoft Office ，但改进了按需唤醒用户的处理方式—如果其组织计划关闭 VM ，但具有按需唤醒功能的用户仍在积极工作， 克隆 VM 时，请勿关闭组织的 VM 稳定性提高功能—从克隆的 VM 中新创建的 VM 中删除 Connection Broker 等角色。改进了 ThinPrint 许可证服务器角色的安装过程改进了 AzureRM 模板处理方式—根据虚拟机运行的硬件返回 Azure 中 VM 可用的所有模板， 不仅租户 Azure 区域提供的模板改进了 vSphere 部署的自动化测试，还包括在每晚电子邮件报告中检查是否安装了 ThinPrint 许可证服务器。在有限的部分情形下，实时扩展的错误修复在某些情形下克隆服务器的错误修复 vCloud 部署 AzureRM 部署中 VM 名称前缀的错误修复在 Google Cloud Platform 中使用自定义计算机大小时报告错误错误修复对启用了 ThinPrint 功能的报告用户的错误修复从 AzureRM 中提供的模板列表中排除了中文版的 Windows



=== CWA" 设置 "

修复不接受满足所需最少字符数的密码的情形在 CSP 的租户选择过程中将 ID 列更改为客户域更新为简化信用卡输入的注册过程



== WCMS 5.2 次要版本： 2018 年 12 月 20 日，星期四

组件： 5.2 Cloud Workspace Management Suite 时间： 2018 年 12 月 20 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间设置

增加了一项 FTP DNS 注册功能，用于在部署单服务器时进行注册，并在部署过程中选择了自动 SSL 自动填充 Azure AD 信息。（租户 ID ，客户端 ID ，密钥）到后端表中，自动安装过程现在将安装 ThinPrint 许可证服务器 11 ，而不是 10



=== 5.2 CWA" 设置 "

修复注册过程完成后将管理员重定向到登录页面的问题描述



== WCMS 5.2 次要版本： 2018 年 12 月 6 日，星期四

组件： 5.2 Cloud Workspace Management Suite 时间： 2018 年 12 月 6 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间工具和服务

支持使用 Win10 操作系统创建服务器提高从虚拟机管理程序加载虚拟机时的速度在 Azure 中创建服务器时返回正确的可用存储类型将每日报告日志记录添加到控制平面的后端，避免出现临时驱动器可能在 Azure 中自动扩展的情况 为未来选择配置模板时显示服务器操作系统的更改奠定基础。错误修复：在 GCP 中不自动扩展驱动器错误修复：使用 Azure Active Directory 域服务时的部署自动化如果配置了多个管理器服务器， 请注意每晚报告中的错误公有云（ Azure ， GCP ）自动测试的错误修复 VMware 部署中的备份错误修复用于确定通过 HyperV 部署创建的新虚拟机上的磁盘空间错误修复用于在 AD 根 OU 为空时收集服务器数据的错误修复在基于配置不当的虚拟机管理程序克隆服务器时提高稳定性



=== 5.2 REST API

在公有云化部署中启用对计算机系列的支持允许为 SDDC 禁用默认资源分配将 DataCollectedDateUTC 添加到服务器的存储详细信息添加计算资源值的功能添加获取详细用户连接状态的新方法在 CMS 中显示错误 删除具有管理员权限的用户时，对于已启用数据的应用程序服务，使用驱动器映射的 Fixed 问题描述并不总是显示 Fixed 问题描述正在通过 CWA Fixed 问题描述导入的客户端和 / 或用户。创建新用户并将应用程序分配到后，此 CWA Fixed 将更新此客户端和 / 或用户 如果是所有用户组，则新用户不会收到应用程序快捷方式。



== WCMS 5.2 次要版本： 2018 年 11 月 1 日，星期四

组件： 5.2 Cloud Workspace Management Suite 时间： 2018 年 11 月 1 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

集成备份的错误修复 CRA 部署中特定用例的错误修复



=== 5.2 Cloud Workspace 工具和服务

启用在创建服务器时返回 Azure arm 部署中可用的存储类型支持多站点 Active Directory 拓扑使用 TestVDCTools 修复使用 Azure Active Directory 域服务时使用问题描述在 AD 根 OU 为空时修复夜间电子邮件报告的错误



=== 5.2 REST API

支持在 Azure Active Directory 域服务时解除用户锁定。注意：请注意，由于复制，可能会有长达 20 分钟的延迟。



== WCMS 5.2 次要版本： 2018 年 10 月 18 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2018 年 10 月 18 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

在数据中心向导中， 启用通配符证书验证常规后台改进和错误修复在应用程序表中添加搜索功能改进了应用程序表中的排序在数据中心配置过程中添加完成 DNS 注册的详细信息包括动态 API 调用响应中的所有子合作伙伴用户和组 应用程序服务修复了在特定实例中租户无法保持迁移模式的错误添加额外已启动的服务器， 每个服务器的共享用户数和每个服务器的最大共享用户数实时扩展详细信息在通过新的数据中心向导进行配置时，将 DNS 验证添加到通配符证书测试中



=== 5.2 云工作空间工具和服务

启用一个选项以返回按 VM 系列分组的所有 VM 大小返回虚拟机管理程序中提供的所有 VM 大小计算应用程序服务用户时修复资源分配为 CMGR1 的自动资源更新启用选项包括通配符证书状态 DataCenterResources Report 启用未来 DNS 增强功能错误修复 修复了 GCP 部署中的驱动器自动扩展问题



=== 5.2 REST API

列出客户端 / 用户时的性能改进支持新的实时扩展功能—配置特 PoweredOnServer ， SharedUsersPerServer 和 MaxSharedUsersPerServer API 现在支持在创建新平台部署时验证通配符证书域可通过新的 API 方法获取所有合作伙伴客户端的用户活动数据

已知问题描述：使用 " 活动用户 " 或 " 用户计数 " 动态分配方法在 Azure 臂部署中估算资源池规模时， " 每台服务器计算的资源 " 摘要错误地将计算机大小显示为基本 A 系列类型，而不是正确的标准 D 系列类型。



== WCMS 5.2 次要版本： 2018 年 9 月 27 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2018 年 9 月 27 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

简化配置收集 VM 在缓存中的显示修复管理应用程序服务时的显示问题



=== 5.2 Cloud Workspace 工具和服务

针对最终用户 MFA 更新 API 与 Azure RM 最新更新测试相结合的模糊用例的错误修复，该测试使用最新的 API 将高级用户术语替换为 VDI 用户更新电子邮件报告，以便为服务器添加额外的 CPU 和 RAM 更新地址报告来自—而不是来自 dcnotifications@independenceit.com 的 dcnotfications@cloudjumper.com 消息允许通过实时扩展来定义每个服务器的用户以及其他 VM 在启动停止的 SDDC/ 部署增强功能时保持启用状态—禁止具有多个 SDDC/ 部署的合作伙伴从一个连接到 另一项稳定性提升—在自动化无法返回用户计数的情况下，请勿对资源计数进行任何更改



== WCMS 5.2 次要版本： 2018 年 9 月 6 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2018 年 9 月 6 日星期四晚上 10 点至晚上 11 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

添加了在自定义应用程序目录中搜索子合作伙伴的功能修复了一个错误，在数据中心模块中刷新屏幕会导致错误提示删除有关最大文件夹名称大小的限制并使浏览文件夹更容易确保资源在 VM 上计数 从不低于指定的最小 CPU 和 RAM 值将高级用户术语重新短语给 VDI 用户修复了一个错误，在该错误中，尽管后端过程成功完成了改进后的服务器名称显示在数据中心创建向导中修复了帐户到期未显示已保存的到期日期，但仍显示了一个通用错误 在 WCMS 中



=== 5.2 Cloud Workspace 工具和服务

修复了 MFA 中的一个错误，即选择电子邮件的用户有时未收到代码允许为用户计数资源分配类型输入额外的 CPU 和 RAM 修复了一个错误，即自动化引擎未在固定的时间问题描述上为所有计算机类型供电有时会使用发生原因 克隆服务器以错误地自动执行先前手动在 FTP 服务器上安装的通配符证书。添加了一个在更新通配符证书后清除旧证书的过程，用于解析问题描述，在使用启用了数据的应用程序服务时， X ：驱动器不会始终映射到最终用户。



== WCMS 5.2 全面上市版本： 2018 年 8 月 10 日，星期四

组件： 5.2 Cloud Workspace Management Suite ；时间： 2018 年 8 月 10 日星期四晚上 10 点东部影响：最终用户可以无中断访问 Cloud Workspace 桌面和应用程序服务。您仍可访问 Cloud Workspace Management Suite 。



=== 5.2 云工作空间管理套件

释放 Web 界面组件以启用上述概述中的功能



=== 5.2 Cloud Workspace 工具和服务

释放后端工具以启用上述概述中的功能



=== 5.2 REST API

 Release API to production to enable the features found in the overview above