= 概述




== 概述

迁移到任何类型的云解决方案时，迁移数据几乎是一项通用要求。虽然管理员负责将数据迁移到其虚拟桌面，但 NetApp 的经验是可以获得的，而且经验证，对于无数客户迁移来说， NetApp 的经验是非常宝贵的。虚拟桌面环境只是一个托管的 Windows 环境，因此可以采用任何所需的方法。

.通常迁移的数据：
* 用户配置文件（桌面，文档，收藏夹等… ）
* 文件服务器共享
* 数据共享（应用程序数据，数据库，备份缓存）


.在虚拟桌面环境中，存储和组织数据的主要位置有两个：
* 用户（通常为 H ： \ ）驱动器：这是对每个用户可见的映射驱动器。
+
** 此路径将映射回 < 驱动器 > ： \home\CustomerCode\user.name 路径
** 每个用户都有自己的 H ： \ 驱动器，无法查看其他用户


* 共享（通常为 I ： \ ）驱动器：这是对所有用户可见的共享映射驱动器
+
** 此路径将映射回 < 驱动器 > ： \data\CustomerCode\ 路径
** 所有用户均可访问此驱动器。其对所含文件夹 / 文件的访问级别在 VDS 的文件夹部分进行管理。






== 通用迁移过程

. 将数据复制到云环境
. 将数据移动到 H ： \ 和 I ： \ 驱动器的相应路径
. 在虚拟桌面环境中分配适当的权限




== FTPS 传输和注意事项



=== 使用 FTPS 进行迁移

. 如果在 CWA 部署过程中启用了 FTPS 服务器角色，请通过登录到 VDS ，导航到报告并运行组织的主客户端报告来收集 FTPS 凭据
. 上传数据
. 将数据移动到 H ： \ 和 I ： \ 驱动器的相应路径
. 通过文件夹模块在虚拟桌面环境中分配适当的权限



NOTE: 通过 FTPS 传输数据时，任何中断都将阻止按预期传输数据。由于虚拟桌面服务管理的服务器每晚重新启动一次，因此标准的夜间传输策略可能会中断。要解决此问题，管理员可以启用迁移模式，以防止 VM 在 1 周内重新启动。

启用迁移模式非常简单—导航到组织，向下滚动到 Virtual Desktop Settings 部分并选中 Migration Mode 复选框，然后单击 Update 。


NOTE: NetApp 建议管理员启用一个合规性设置，通过强化部署的网关等来帮助组织满足 PCI ， HIPAA 和 NIST 控制的要求。这样，如果启用了默认 FTP 服务器角色，则也不允许通过端口 21 接受默认的未加密传输。FileZilla 不允许使用 SFTP ，这意味着应使用 FTPS 通过端口 990 进行连接。

要启用此设置，请连接到 CMGR1 并导航到 CwVmAutomationService 程序，然后启用 PCI v3 合规性。



== 同步工具和注意事项

企业文件同步和共享通常称为 EFSS 或同步工具，在迁移数据时非常有用，因为该工具会捕获双方的更改，直到转换为止。Office 365 附带的 OneDrive 等工具可以帮助您同步文件服务器数据。如果 VDI 用户部署中的用户和虚拟机之间存在 1 ： 1 关系，则此功能也很有用，前提是用户不会尝试将共享内容同步到其 VDI 服务器，而共享数据只能部署一次（通常为 I ： \ ） 推动整个企业使用。迁移 SQL 和类似数据（打开的文件）

.常见的同步和 / 或迁移解决方案不会传输打开的文件，其中包括以下文件类型：
* 邮箱（ .ost ）文件
* QuickBooks 文件
* Microsoft Access 文件
* SQL 数据库


这意味着，如果整个文件的一个元素（例如，显示 1 个新电子邮件）或数据库（在应用程序的系统中输入 1 个新记录），则整个文件将与标准同步工具（例如， Dropbox ）不同。 会认为它是一个全新的文件，需要再次移动。如果需要，可以从第三方提供商购买专用工具。

处理这些迁移的另一种常见方法是，提供对第三方 VAR 的访问权限，第三方 VAR 通常简化了数据库的导入 / 导出。



== 运输驱动器

许多数据中心提供商不再提供硬盘驱动器，或者他们要求您遵循其特定的策略和程序。

Microsoft Azure 支持企业使用 Azure Data Box ，管理员可以通过与其 Microsoft 代表进行协调来利用它。
