= 概述




== 概述

VDS 将概念组织到逻辑层次结构的不同层中。本文有助于概述它们如何组合在一起。



=== VDS 组织方案

VDS 管理门户位于 https://manage.vds.netapp.com[]。此 Web 界面是一个单一管理平台，用于管理所有与 VDS 相关的对象。在 VDS Web UI 中，存在以下组件和逻辑容器层次结构。



==== VDS 部署

_Deployment_ 是一个 VDS 概念，它经过组织并包含 _VDS Workspace （ s ） _ 。在某些部署架构中，一个部署可以包含多个 VDS 工作空间。


NOTE: 在一个部署中运行多个 VDS 工作空间称为 " 多租户 " ，这只是 RDS 部署中的一个选项， AVD 部署不支持此方法。

部署由其 Active Directory 域定义， AD 域和部署之间存在 1 ： 1 关系。

为了支持在部署中的所有 VDS 工作空间之间共享的部署，部署了某些 VM 资源。例如，每个部署都包含一个名为 "cvgr1" 的 VM ，该 VM 是一个运行 VDS 应用程序的服务器，一个 SQL Express 数据库，便于在部署中管理 VDS 工作空间（以及包含的资源）。



==== VDS 工作空间


WARNING: "* VDS* 工作空间 " 与 "* AVD* 工作空间 " 之间存在差异。

VDS 工作空间是部署中用于客户端（最终用户）资源的逻辑容器。这些资源包括虚拟机（用于会话主机，应用程序服务器，数据库服务器，文件服务器等），虚拟网络， 存储和其他虚拟机管理程序基础架构。

VDS 工作空间还包含管理功能，用于管理用户，安全组，工作负载计划，应用程序，自动化， VM 和 AVD 配置。

通常， VDS 工作空间与一家公司或（在企业部署中）一个业务单位保持一致。



==== VDS 站点

在一个部署中，可以创建多个站点来表示不同的基础架构提供商，所有这些站点都在一个部署中进行管理。

当一家公司或业务部门需要跨多个物理位置（例如北美和欧洲，中东和非洲）托管用户和应用程序，订阅虚拟机管理程序（以便根据业务单位调整成本）甚至需要管理程序（例如 Azure ， Google Compute 和 vSphere 上的内部 HCI 用户）时，这将非常有用。



==== AVD 工作空间


WARNING: "* VDS* 工作空间 " 与 "* AVD* 工作空间 " 之间存在差异。

AVD 工作空间是一个逻辑容器，位于 VDS 工作空间和 VDS 站点内。它可以与 VDS 站点类似使用，用于在同一部署中对管理和操作策略进行分段。



==== AVD 主机池

AVD 主机池是一个逻辑容器，位于 AVD 工作空间中，用于存放会话主机和应用程序组用户，以便为用户会话提供服务器并控制对各个资源的访问。



==== AVD 应用程序组

每个 AVD 主机池都以一个 " 桌面 " 应用程序组开头。可以将用户和 / 或组分配给此（或其他）应用程序组，以允许分配的用户访问应用程序组中的资源。

可以在 VDS 的主机池中创建其他应用程序组。所有其他应用程序组均为 "RemoteApp" 应用程序组，可提供 RemoteApp 资源，而不是提供完整的 Windows 桌面体验。
