= 概述
:allow-uri-read: 



NOTE: 对于 CWS 5.0 版，不再存在重复发布的版本—所有版本都将视为修补程序。



== 概述

CloudJumper 发布了 Cloud Workspace Suite 5.0 ，从 2016 年第 4 季度开始全面实施。此版本更新了 CWS API 和管理控制界面。此版本是一项重大更改，与 4.x 版实体不 " 向后兼容 " 。

在将所有合作伙伴软件定义的数据中心（ SDDC ）升级到 5.0 平台之前，版本 4.x 将继续受支持，升级将由 Cloud跳 线与每个合作伙伴协调完成，并且不会中断现有服务。过渡无需支付升级费用或实施成本。CWS 5 继续支持先前版本的所有功能，并扩展了可增强管理员和最终用户体验的新功能，进一步改进了以前版本的 Cloud Workspace Suite 推出的屡获殊荣的自动化和流程编排功能。

在 CWS 5.0 中， Cloud跳 线已将所有平台 API 重新写入 REST API 格式，并完全淘汰了早期的 SOAP API 。经过更新的架构将使 Cloud跳 线能够更轻松，更快速地进一步增强功能，并为外部开发人员提供更加友好的环境，使他们能够基于 Cloud Workspace 扩展其服务和产品。



== 亮点

* 完成 UI/UX 重写
* Azure AD 集成
* Azure SDDC 自助服务部署
* 应用程序服务
* 资源计划
* 实时服务器扩展—跨平台
* 自动化服务器克隆—跨平台
* 按客户端自定义驱动器共享




== 主要功能：



=== Azure Active Directory （ AD ）集成

* 将 SDDC 构建为私有云 Active Directory 或使用 Microsoft Azure-ad-a-Service
* 将 CWS 与 Office365 结合使用
* 支持基于 Azure 的 SSO 和 MFA




=== Azure SDDC 自助服务部署

* 与 Azure 完全集成
* 快速部署新 SDDC
* 在 Azure 中为任何工作负载部署私有企业云，包括受管理的 Cloud Workspace ： WAAS ，应用服务，私有 Web 应用程序和 SharePoint




=== 应用程序服务

* 将应用程序孤岛部署为将应用程序发布为独立的服务构建块
* 从 ‘公有 ' 应用程序服务器交付给多个自定义实体的应用程序
* 应用程序安装在单个应用程序专用服务器池中
* 应用程序与用户配置文件和数据层要求分离
* 构建可超扩展的应用程序服务
* 可以将多个应用程序服务组合到用户集合中
* CWS 许可证跟踪和使用情况报告




=== 实时服务器扩展—跨平台

* 自动智能扩展服务器资源 / 活动服务器
* 在用户负载发生变化时，通过动态增加 / 减少来严格管理服务器资源
* 根据工作负载的变化自动纵向扩展服务器资源




=== 自动化服务器克隆—跨平台

* 自动增加服务器，直到定义的用户数量增加时计数可用性为止
* 向可用资源池添加其他服务器
* 结合 CWS 实时服务器扩展功能，创建完全自动化的解决方案




=== 资源计划

* 按客户计划服务时间
* 公有云的成本控制
* 不使用时关闭系统，并按预定义计划重新激活

