= 概述
:allow-uri-read: 




== 概述

对应用程序错误进行故障排除是一种常见的管理实践，它不涉及 VDS 本身，但它在很大程度上由 VDS 及其为管理员提供的控制级别提供帮助。虽然 NetApp VDS 不会为客户解决这些问题，但根据我们的经验，我们可以在确定以下一些基本信息之后向管理员提供建议，以便深入挖掘并与最终用户和 / 或第三方进行故障排除。

* 遇到问题描述的用户的名称
* 用户正在使用的应用程序的名称
* 用户会话所在的服务器
* 重现问题描述的步骤




== 查看工具



=== 监控

确定用户正在使用的服务器后，请检查您的监控解决方案以验证资源（ CPU 和 RAM ）消耗是否处于正常水平。您还可以验证应用程序特定的要求（如果未运行，则会出现发生原因问题的特殊服务）是否正常运行。在这种情况下，可能已触发高级设置，例如对所述服务的上 / 下监控。



=== 防病毒

作为同时有权访问服务器和 Azure Active Directory 的管理员，您可以查看发现的内容以及设置的策略。如果出现意外情况，可能会影响您的应用程序。



=== 其他工具

某些应用程序需要额外的组件，例如无限期登录的服务帐户或对物理设备（例如现场网络设备或制造设备或诊断实用程序）的 VPN 。在这些情况下，应用程序特定的错误可能是由应用程序的安装方式或其设置的配置方式以外的其他原因引起的。



=== 扩展对第三方的访问

应用程序和 / 或其数据库通常由软件供应商（ ISV ）自己或该软件的配置，管理和集成方面的第三方专家进行安装，配置和支持。在这些情况下，您需要将临时管理访问扩展到以下步骤： link:Management.System_Administration.provide_3rd_party_access.html["为第三方提供临时访问权限"]

最好在升级或更新完成后或问题描述解决后关闭这些第三方帐户。

在许多情况下，此级别的故障排除要求与 ISV 签订软件维护合同。如果没有这样做，则 ISV 可能无法为您提供帮助，除非已完成此操作。


NOTE: 问题描述故障排除也可能与最终用户正在使用的硬件（桌面，笔记本电脑，瘦客户端等）相关。例如，升级用户的笔记本电脑可能会将计算机锁定在瘦客户端配置文件的眼睛中，这意味着最终用户无法访问允许他们登录到其虚拟桌面的工具。在这种情况下，可能需要签订硬件维护合同，然后制造商才能为您提供帮助。
